### ISSUE TITLE
pywsgi: Value must be a native string

### ISSUE THREAD

**Issue by janhh** [ThiefMaster/maildump#18]
I recieve unicode error from pywsgi on Debian 8.

I installed maildump with:
sudo apt-get install python-pip python-dev
sudo /usr/bin/pip install maildump==0.5.3

Output when accessing localhost:1081:
> vagrant@vagrant-debian-jessie:~$ maildump --http-port 1081 --smtp-port 1026 -f
> [2016-05-20 11:01:47]  NOTICE    maildump: Starting web server on http://127.0.0.1:1081
> FAILED to start flash policy server: [Errno 98] Address already in use: ('127.0.0.1', 10843)
> [2016-05-20 11:01:47]  NOTICE    maildump: Starting smtp server on 127.0.0.1:1026
> [2016-05-20 11:01:47]  INFO      maildump.db: Using database :memory:
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
>     result = self._run(*self.args, **self.kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 25, in _handle_and_close_when_done
>     return handle(*args_tuple)
>   File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 124, in handle
>     handler.handle()
>   File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 443, in handle
>     result = self.handle_one_request()
>   File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 658, in handle_one_request
>     self.handle_one_response()
>   File "/usr/local/lib/python2.7/dist-packages/socketio/handler.py", line 122, in handle_one_response
>     return self._do_handshake(handshake_tokens.groupdict())
>   File "/usr/local/lib/python2.7/dist-packages/socketio/handler.py", line 64, in _do_handshake
>     self.write_smart(data)
>   File "/usr/local/lib/python2.7/dist-packages/socketio/handler.py", line 88, in write_smart
>     self.write_plain_result(data)
>   File "/usr/local/lib/python2.7/dist-packages/socketio/handler.py", line 78, in write_plain_result
>     ("Content-Type", "text/plain"),
>   File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 778, in start_response
>     raise UnicodeError("The value must be a native string", header, value)
> UnicodeError: ('The value must be a native string', 'Access-Control-Max-Age', 3600)
> <Greenlet at 0x7f2618784cd0: _handle_and_close_when_done(<bound method SocketIOServer.handle of <SocketIOSe, <bound method SocketIOServer.do_close of <SocketIO, (<socket at 0x7f2618503f50 fileno=[Errno 9] Bad fi)> failed with UnicodeError
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
>     result = self._run(*self.args, **self.kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 25, in _handle_and_close_when_done
>     return handle(*args_tuple)
>   File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 124, in handle
>     handler.handle()
>   File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 443, in handle
>     result = self.handle_one_request()
>   File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 658, in handle_one_request
>     self.handle_one_response()
>   File "/usr/local/lib/python2.7/dist-packages/socketio/handler.py", line 122, in handle_one_response
>     return self._do_handshake(handshake_tokens.groupdict())
>   File "/usr/local/lib/python2.7/dist-packages/socketio/handler.py", line 64, in _do_handshake
>     self.write_smart(data)
>   File "/usr/local/lib/python2.7/dist-packages/socketio/handler.py", line 88, in write_smart
>     self.write_plain_result(data)
>   File "/usr/local/lib/python2.7/dist-packages/socketio/handler.py", line 78, in write_plain_result
>     ("Content-Type", "text/plain"),
>   File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 778, in start_response
>     raise UnicodeError("The value must be a native string", header, value)
> UnicodeError: ('The value must be a native string', 'Access-Control-Max-Age', 3600)
> <Greenlet at 0x7f2618784eb0: _handle_and_close_when_done(<bound method SocketIOServer.handle of <SocketIOSe, <bound method SocketIOServer.do_close of <SocketIO, (<socket at 0x7f2618527590 fileno=[Errno 9] Bad fi)> failed with UnicodeError

Other than that, MailDump seems to work fine. We need to refresh web browser to see changes, but other than that it does its job as a MailCatcher alternative. Thanks for the good work.

**Comment by ThiefMaster** [comment]
Strange, never seen this error before. I'll have a look. Does this also happen if you install it inside a clean virtualenv?

**Comment by janhh** [comment]
Hi. Yes, it's the same result inside virtualenv.

Debian ships with Python 2.7.9, tried with 2.7.11 and virtualenv just now, same result. Here's installed dependencies.

> (maildumptest) vagrant@vagrant-debian-jessie:~/tmp$ pip freeze
> beautifulsoup4==4.4.1
> cssmin==0.2.0
> cssprefixer==1.4.1
> cssutils==1.0.1
> docutils==0.12
> enum34==1.1.6
> Flask==0.10.1
> Flask-Assets==0.11
> gevent==1.1.1
> gevent-socketio==0.3.6
> gevent-websocket==0.9.5
> greenlet==0.4.9
> html5lib==0.9999999
> itsdangerous==0.24
> Jinja2==2.8
> lockfile==0.12.2
> Logbook==0.12.5
> maildump==0.5.3
> MarkupSafe==0.23
> passlib==1.6.5
> pathlib==1.0.1
> pyScss==1.3.4
> python-daemon==2.1.1
> pytz==2016.4
> six==1.10.0
> webassets==0.11.1
> Werkzeug==0.11.9

**Comment by ThiefMaster** [comment]
Hm, probably caused by one of the dependencies releasing an update breaking backwards compatibility. I should probably specify some maximum versions...

Could you check if it works with `gevent==1.0.1` (or any other 1.0.x version)? That's what I'm using on my machine atm. If it works I might need to require `gevent<1.1`

**Comment by janhh** [comment]
Have installed gevent 1.0.1 now.

> (maildumptest) vagrant@vagrant-debian-jessie:~/tmp$ pip freeze | grep gevent
> gevent==1.0.1
> gevent-socketio==0.3.6
> gevent-websocket==0.9.5

Another error appeared, and MailDump exits.
 
> (maildumptest) vagrant@vagrant-debian-jessie:~/tmp$ maildump --http-ip 0.0.0.0 -f
> Traceback (most recent call last):
>   File "/home/vagrant/tmp/maildumptest/bin/maildump", line 11, in <module>
>     sys.exit(main())
>   File "/home/vagrant/tmp/maildumptest/local/lib/python2.7/site-packages/maildump_runner/__main__.py", line 130, in main
>     context.open()
>   File "/home/vagrant/tmp/maildumptest/local/lib/python2.7/site-packages/maildump_runner/geventdaemon.py", line 43, in open
>     self._apply_monkey_patch()
>   File "/home/vagrant/tmp/maildumptest/local/lib/python2.7/site-packages/maildump_runner/geventdaemon.py", line 57, in _apply_monkey_patch
>     gevent.monkey.patch_all()
>   File "/home/vagrant/tmp/maildumptest/local/lib/python2.7/site-packages/gevent/monkey.py", line 185, in patch_all
>     patch_socket(dns=dns, aggressive=aggressive)
>   File "/home/vagrant/tmp/maildumptest/local/lib/python2.7/site-packages/gevent/monkey.py", line 124, in patch_socket
>     from gevent import socket
>   File "/home/vagrant/tmp/maildumptest/local/lib/python2.7/site-packages/gevent/socket.py", line 659, in <module>
>     from gevent.ssl import sslwrap_simple as ssl, SSLError as sslerror, SSLSocket as SSLType
>   File "/home/vagrant/tmp/maildumptest/local/lib/python2.7/site-packages/gevent/ssl.py", line 386, in <module>
>     def get_server_certificate(addr, ssl_version=PROTOCOL_SSLv3, ca_certs=None):
> NameError: name 'PROTOCOL_SSLv3' is not defined

Naturally, going back to gevent 1.1.1 brings back the original error.

**Comment by yyyk-bp** [comment]
I get the same. I try to use `gevent==1.0.2`, and it's seems to work fine.

related: https://github.com/gevent/gevent/issues/513

**Comment by janhh** [comment]
Other than

**Comment by ThiefMaster** [comment]
Cannot reproduce the SSL issue (maildump doesn't do SSL anyway), but I've released a new version that requires `gevent<1.1` which fixes the unicode problem for me.
