### ISSUE TITLE
Flask deprecation notice

### ISSUE THREAD

**Issue by ad-m** [ThiefMaster/maildump#22]
``
/tmp/tmp.lMebgO9tEp/local/lib/python2.7/site-packages/maildump/web.py:7: ExtDeprecationWarning: Importing flask.ext.assets is deprecated, use flask_assets instead.
  from flask.ext.assets import Environment, Bundle
``

**Comment by ThiefMaster** [comment]
Can be safely ignored, but if you want to make a PR I'd appreciate it - 
it's an easy fix :)

**Comment by RibanKeke** [comment]
Hi,
We are actually using maildump and it's quite cool.
I'll be more then happy to fix this one for a start.
I'll send a pull request soon.

**Comment by mikicz** [comment]
I think this was fixed in https://github.com/ThiefMaster/maildump/commit/dbe3b05e2ca2b40b06437164ed135b5e79a69e33

So the ticket can be closed now
