### ISSUE TITLE
Add Windows support ?

### ISSUE THREAD

**Issue by pakal** [ThiefMaster/maildump#29]
The "pwd" module requested by maildump is not existing on windows, so launching maildump crashes.

**Comment by ThiefMaster** [comment]
PRs are welcome (personally I don't care enough about running this on Window, sorry).
Does gevent even work on windows though?

**Comment by pakal** [comment]
Ok no problem I'll just take another mailctacher-like since it's only for a temporary need ^^

Yes gevent seems to work fine on Windows, even if compiling extensions is always a bit trickier when no wheel exists for the particular Python version.
