### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [ThiefMaster/maildump#36]
Was trying it out on Windows, it spits out:

```stdout
    import pwd
ModuleNotFoundError: No module named 'pwd'
```

While in setup we see:
```
  Environment :: Web Environment
```

I guess it might be awesome to add windows support. I am willing to do it!

**Comment by ThiefMaster** [comment]
Personally I have no interest in adding Windows support or maintaining it.

But if someone else (e.g. you) is willing to do that and it doesn't complicate things too much (especially the logic to run it as a daemon) fine.

**Comment by Abdur-rahmaanJ** [comment]
I plan to add it to the dev workflow of the [shopyo](https://github.com/Abdur-rahmaanJ/shopyo) project of mine as i don't want a ruby or node package and this seems the most viable option. I'll guess i have to look at the internals docs.

**Comment by Abdur-rahmaanJ** [comment]
Abandoned Idea
